"""
Permissions de base pour l'application Core
"""
from .base_permissions import (
    BasePermission,
    IsOwnerOrReadOnly,
    IsOwnerOrAdmin,
    IsAdminOrReadOnly,
    IsAuthenticatedOrReadOnly,
    IsStaffOrReadOnly,
    IsSuperuserOrReadOnly,
    IsOwnerOrStaff,
    IsOwnerOrAdminOrReadOnly,
    IsOwnerOrStaffOrReadOnly,
    IsOwnerOrSuperuser,
    IsOwnerOrStaffOrSuperuser,
    IsOwnerOrAdminOrStaff,
    IsOwnerOrAdminOrStaffOrReadOnly,
    IsOwnerOrAdminOrStaffOrSuperuser,
)

from .custom_permissions import (
    CanViewOwnData,
    CanEditOwnData,
    CanDeleteOwnData,
    CanViewUserData,
    CanEditUserData,
    CanDeleteUserData,
    CanManageUsers,
    CanManagePermissions,
    CanManageRoles,
    CanManageGroups,
    CanViewAuditLogs,
    CanManageSystemSettings,
    CanAccessAdminPanel,
    CanViewReports,
    CanExportData,
    CanImportData,
    CanManageNotifications,
    CanManageSecurity,
    CanViewAnalytics,
    CanManageIntegrations,
)

from .permission_classes import (
    CorePermission,
    AuthenticationPermission,
    UserPermission,
    NotificationPermission,
    SecurityPermission,
    PermissionPermission,
    RolePermission,
    GroupPermission,
    AuditPermission,
    SystemPermission,
    ReportPermission,
    IntegrationPermission,
)

__all__ = [
    # Base permissions
    'BasePermission',
    'IsOwnerOrReadOnly',
    'IsOwnerOrAdmin',
    'IsAdminOrReadOnly',
    'IsAuthenticatedOrReadOnly',
    'IsStaffOrReadOnly',
    'IsSuperuserOrReadOnly',
    'IsOwnerOrStaff',
    'IsOwnerOrAdminOrReadOnly',
    'IsOwnerOrStaffOrReadOnly',
    'IsOwnerOrSuperuser',
    'IsOwnerOrStaffOrSuperuser',
    'IsOwnerOrAdminOrStaff',
    'IsOwnerOrAdminOrStaffOrReadOnly',
    'IsOwnerOrAdminOrStaffOrSuperuser',
    
    # Custom permissions
    'CanViewOwnData',
    'CanEditOwnData',
    'CanDeleteOwnData',
    'CanViewUserData',
    'CanEditUserData',
    'CanDeleteUserData',
    'CanManageUsers',
    'CanManagePermissions',
    'CanManageRoles',
    'CanManageGroups',
    'CanViewAuditLogs',
    'CanManageSystemSettings',
    'CanAccessAdminPanel',
    'CanViewReports',
    'CanExportData',
    'CanImportData',
    'CanManageNotifications',
    'CanManageSecurity',
    'CanViewAnalytics',
    'CanManageIntegrations',
    
    # Permission classes
    'CorePermission',
    'AuthenticationPermission',
    'UserPermission',
    'NotificationPermission',
    'SecurityPermission',
    'PermissionPermission',
    'RolePermission',
    'GroupPermission',
    'AuditPermission',
    'SystemPermission',
    'ReportPermission',
    'IntegrationPermission',
]



