"""
Utilitaires communs pour l'application Core
"""
from .helpers import (
    generate_random_string,
    generate_slug,
    format_file_size,
    format_duration,
    get_client_ip,
    get_user_agent,
    is_valid_email,
    is_valid_phone,
    clean_html,
    truncate_text,
    convert_to_snake_case,
    convert_to_camel_case,
    get_file_extension,
    get_mime_type,
    hash_password,
    verify_password,
    generate_otp,
    generate_token,
    parse_date,
    format_date,
    get_timezone_offset,
    calculate_age,
    is_business_day,
    get_next_business_day,
    get_previous_business_day,
)

from .validators import (
    validate_email,
    validate_phone,
    validate_password,
    validate_url,
    validate_ip_address,
    validate_file_size,
    validate_file_type,
    validate_image_dimensions,
    validate_json,
    validate_slug,
    validate_hex_color,
    validate_credit_card,
    validate_postal_code,
    validate_iban,
    validate_swift_code,
    validate_tax_id,
    validate_ssn,
)

from .decorators import (
    cache_result,
    rate_limit,
    retry_on_failure,
    log_execution_time,
    require_permissions,
    require_authentication,
    validate_request_data,
    handle_exceptions,
    async_operation,
    background_task,
)

from .exceptions import (
    CoreException,
    ValidationError,
    AuthenticationError,
    PermissionError,
    NotFoundError,
    ConflictError,
    RateLimitError,
    CacheError,
    ExternalServiceError,
    ConfigurationError,
)

from .serializers import (
    BaseSerializer,
    TimestampedSerializer,
    SoftDeleteSerializer,
    StatusSerializer,
    OrderingSerializer,
    SlugSerializer,
    CacheSerializer,
    CreatedBySerializer,
    UpdatedBySerializer,
)

from .managers import (
    BaseManager,
    TimestampedManager,
    SoftDeleteManager,
    StatusManager,
    OrderingManager,
    CacheManager,
    CreatedByManager,
    UpdatedByManager,
)

__all__ = [
    # Helpers
    'generate_random_string',
    'generate_slug',
    'format_file_size',
    'format_duration',
    'get_client_ip',
    'get_user_agent',
    'is_valid_email',
    'is_valid_phone',
    'clean_html',
    'truncate_text',
    'convert_to_snake_case',
    'convert_to_camel_case',
    'get_file_extension',
    'get_mime_type',
    'hash_password',
    'verify_password',
    'generate_otp',
    'generate_token',
    'parse_date',
    'format_date',
    'get_timezone_offset',
    'calculate_age',
    'is_business_day',
    'get_next_business_day',
    'get_previous_business_day',
    
    # Validators
    'validate_email',
    'validate_phone',
    'validate_password',
    'validate_url',
    'validate_ip_address',
    'validate_file_size',
    'validate_file_type',
    'validate_image_dimensions',
    'validate_json',
    'validate_slug',
    'validate_hex_color',
    'validate_credit_card',
    'validate_postal_code',
    'validate_iban',
    'validate_swift_code',
    'validate_tax_id',
    'validate_ssn',
    
    # Decorators
    'cache_result',
    'rate_limit',
    'retry_on_failure',
    'log_execution_time',
    'require_permissions',
    'require_authentication',
    'validate_request_data',
    'handle_exceptions',
    'async_operation',
    'background_task',
    
    # Exceptions
    'CoreException',
    'ValidationError',
    'AuthenticationError',
    'PermissionError',
    'NotFoundError',
    'ConflictError',
    'RateLimitError',
    'CacheError',
    'ExternalServiceError',
    'ConfigurationError',
    
    # Serializers
    'BaseSerializer',
    'TimestampedSerializer',
    'SoftDeleteSerializer',
    'StatusSerializer',
    'OrderingSerializer',
    'SlugSerializer',
    'CacheSerializer',
    'CreatedBySerializer',
    'UpdatedBySerializer',
    
    # Managers
    'BaseManager',
    'TimestampedManager',
    'SoftDeleteManager',
    'StatusManager',
    'OrderingManager',
    'CacheManager',
    'CreatedByManager',
    'UpdatedByManager',
]

