"""
Enums et choix pour l'application Core
"""
from django.db import models


class StatusChoices(models.TextChoices):
    """Choix pour les statuts"""
    DRAFT = 'draft', 'Brouillon'
    ACTIVE = 'active', 'Actif'
    INACTIVE = 'inactive', 'Inactif'
    ARCHIVED = 'archived', 'Archivé'
    PENDING = 'pending', 'En attente'
    APPROVED = 'approved', 'Approuvé'
    REJECTED = 'rejected', 'Rejeté'
    SUSPENDED = 'suspended', 'Suspendu'
    DELETED = 'deleted', 'Supprimé'


class UserRoleChoices(models.TextChoices):
    """Choix pour les rôles utilisateur"""
    SUPERUSER = 'superuser', 'Super Utilisateur'
    ADMIN = 'admin', 'Administrateur'
    MODERATOR = 'moderator', 'Modérateur'
    USER = 'user', 'Utilisateur'
    GUEST = 'guest', 'Invité'
    MANAGER = 'manager', 'Gestionnaire'
    EDITOR = 'editor', 'Éditeur'
    VIEWER = 'viewer', 'Visualiseur'


class NotificationTypeChoices(models.TextChoices):
    """Choix pour les types de notifications"""
    EMAIL = 'email', 'Email'
    SMS = 'sms', 'SMS'
    PUSH = 'push', 'Push'
    IN_APP = 'in_app', 'Dans l\'application'
    WEBHOOK = 'webhook', 'Webhook'
    SLACK = 'slack', 'Slack'
    TEAMS = 'teams', 'Microsoft Teams'
    DISCORD = 'discord', 'Discord'


class SecurityLevelChoices(models.TextChoices):
    """Choix pour les niveaux de sécurité"""
    LOW = 'low', 'Faible'
    MEDIUM = 'medium', 'Moyen'
    HIGH = 'high', 'Élevé'
    CRITICAL = 'critical', 'Critique'
    EMERGENCY = 'emergency', 'Urgence'


class PermissionTypeChoices(models.TextChoices):
    """Choix pour les types de permissions"""
    READ = 'read', 'Lecture'
    WRITE = 'write', 'Écriture'
    DELETE = 'delete', 'Suppression'
    EXECUTE = 'execute', 'Exécution'
    MANAGE = 'manage', 'Gestion'
    ADMIN = 'admin', 'Administration'
    VIEW = 'view', 'Visualisation'
    CREATE = 'create', 'Création'
    UPDATE = 'update', 'Mise à jour'
    APPROVE = 'approve', 'Approbation'
    REJECT = 'reject', 'Rejet'


class FileTypeChoices(models.TextChoices):
    """Choix pour les types de fichiers"""
    IMAGE = 'image', 'Image'
    DOCUMENT = 'document', 'Document'
    VIDEO = 'video', 'Vidéo'
    AUDIO = 'audio', 'Audio'
    ARCHIVE = 'archive', 'Archive'
    CODE = 'code', 'Code'
    DATA = 'data', 'Données'
    OTHER = 'other', 'Autre'


class LanguageChoices(models.TextChoices):
    """Choix pour les langues"""
    FRENCH = 'fr', 'Français'
    ENGLISH = 'en', 'English'
    SPANISH = 'es', 'Español'
    GERMAN = 'de', 'Deutsch'
    ITALIAN = 'it', 'Italiano'
    PORTUGUESE = 'pt', 'Português'
    RUSSIAN = 'ru', 'Русский'
    CHINESE = 'zh', '中文'
    JAPANESE = 'ja', '日本語'
    KOREAN = 'ko', '한국어'
    ARABIC = 'ar', 'العربية'
    HINDI = 'hi', 'हिन्दी'


class TimezoneChoices(models.TextChoices):
    """Choix pour les fuseaux horaires"""
    UTC = 'UTC', 'UTC'
    PARIS = 'Europe/Paris', 'Paris'
    LONDON = 'Europe/London', 'Londres'
    NEW_YORK = 'America/New_York', 'New York'
    LOS_ANGELES = 'America/Los_Angeles', 'Los Angeles'
    TOKYO = 'Asia/Tokyo', 'Tokyo'
    BEIJING = 'Asia/Shanghai', 'Pékin'
    SYDNEY = 'Australia/Sydney', 'Sydney'
    DUBAI = 'Asia/Dubai', 'Dubaï'
    MOSCOW = 'Europe/Moscow', 'Moscou'


class CurrencyChoices(models.TextChoices):
    """Choix pour les devises"""
    EUR = 'EUR', 'Euro (€)'
    USD = 'USD', 'Dollar US ($)'
    GBP = 'GBP', 'Livre Sterling (£)'
    JPY = 'JPY', 'Yen Japonais (¥)'
    CNY = 'CNY', 'Yuan Chinois (¥)'
    CAD = 'CAD', 'Dollar Canadien (C$)'
    AUD = 'AUD', 'Dollar Australien (A$)'
    CHF = 'CHF', 'Franc Suisse (CHF)'
    SEK = 'SEK', 'Couronne Suédoise (kr)'
    NOK = 'NOK', 'Couronne Norvégienne (kr)'
    DKK = 'DKK', 'Couronne Danoise (kr)'
    PLN = 'PLN', 'Zloty Polonais (zł)'
    CZK = 'CZK', 'Couronne Tchèque (Kč)'
    HUF = 'HUF', 'Forint Hongrois (Ft)'
    RON = 'RON', 'Leu Roumain (lei)'
    BGN = 'BGN', 'Lev Bulgare (лв)'
    HRK = 'HRK', 'Kuna Croate (kn)'
    RSD = 'RSD', 'Dinar Serbe (дин)'
    TRY = 'TRY', 'Livre Turque (₺)'
    RUB = 'RUB', 'Rouble Russe (₽)'
    UAH = 'UAH', 'Hryvnia Ukrainienne (₴)'
    BRL = 'BRL', 'Real Brésilien (R$)'
    MXN = 'MXN', 'Peso Mexicain ($)'
    ARS = 'ARS', 'Peso Argentin ($)'
    CLP = 'CLP', 'Peso Chilien ($)'
    COP = 'COP', 'Peso Colombien ($)'
    PEN = 'PEN', 'Sol Péruvien (S/)'
    ZAR = 'ZAR', 'Rand Sud-Africain (R)'
    EGP = 'EGP', 'Livre Égyptienne (E£)'
    NGN = 'NGN', 'Naira Nigériane (₦)'
    KES = 'KES', 'Shilling Kenyan (KSh)'
    MAD = 'MAD', 'Dirham Marocain (MAD)'
    TND = 'TND', 'Dinar Tunisien (DT)'
    DZD = 'DZD', 'Dinar Algérien (DA)'
    LYD = 'LYD', 'Dinar Libyen (LD)'
    SDG = 'SDG', 'Livre Soudanaise (SDG)'
    ETB = 'ETB', 'Birr Éthiopien (Br)'
    UGX = 'UGX', 'Shilling Ougandais (USh)'
    TZS = 'TZS', 'Shilling Tanzanien (TSh)'
    KWD = 'KWD', 'Dinar Koweïtien (KD)'
    SAR = 'SAR', 'Riyal Saoudien (﷼)'
    AED = 'AED', 'Dirham Émirati (د.إ)'
    QAR = 'QAR', 'Riyal Qatari (﷼)'
    BHD = 'BHD', 'Dinar Bahreïni (BD)'
    OMR = 'OMR', 'Rial Omanais (﷼)'
    JOD = 'JOD', 'Dinar Jordanien (JD)'
    LBP = 'LBP', 'Livre Libanaise (ل.ل)'
    ILS = 'ILS', 'Shekel Israélien (₪)'
    INR = 'INR', 'Roupie Indienne (₹)'
    PKR = 'PKR', 'Roupie Pakistanaise (₨)'
    BDT = 'BDT', 'Taka Bangladeshi (৳)'
    LKR = 'LKR', 'Roupie Sri Lankaise (₨)'
    NPR = 'NPR', 'Roupie Népalaise (₨)'
    AFN = 'AFN', 'Afghani Afghan (؋)'
    KZT = 'KZT', 'Tenge Kazakhstanais (₸)'
    UZS = 'UZS', 'Som Ouzbek (лв)'
    KGS = 'KGS', 'Som Kirghiz (лв)'
    TJS = 'TJS', 'Somoni Tadjik (SM)'
    TMT = 'TMT', 'Manat Turkmène (T)'
    AZN = 'AZN', 'Manat Azerbaïdjanais (₼)'
    AMD = 'AMD', 'Dram Arménien (֏)'
    GEL = 'GEL', 'Lari Géorgien (₾)'
    MDL = 'MDL', 'Leu Moldave (L)'
    BYN = 'BYN', 'Rouble Biélorusse (Br)'
    KZT = 'KZT', 'Tenge Kazakhstanais (₸)'
    UZS = 'UZS', 'Som Ouzbek (лв)'
    KGS = 'KGS', 'Som Kirghiz (лв)'
    TJS = 'TJS', 'Somoni Tadjik (SM)'
    TMT = 'TMT', 'Manat Turkmène (T)'
    AZN = 'AZN', 'Manat Azerbaïdjanais (₼)'
    AMD = 'AMD', 'Dram Arménien (֏)'
    GEL = 'GEL', 'Lari Géorgien (₾)'
    MDL = 'MDL', 'Leu Moldave (L)'
    BYN = 'BYN', 'Rouble Biélorusse (Br)'


class CountryChoices(models.TextChoices):
    """Choix pour les pays"""
    FRANCE = 'FR', 'France'
    UNITED_STATES = 'US', 'États-Unis'
    UNITED_KINGDOM = 'GB', 'Royaume-Uni'
    GERMANY = 'DE', 'Allemagne'
    ITALY = 'IT', 'Italie'
    SPAIN = 'ES', 'Espagne'
    PORTUGAL = 'PT', 'Portugal'
    NETHERLANDS = 'NL', 'Pays-Bas'
    BELGIUM = 'BE', 'Belgique'
    SWITZERLAND = 'CH', 'Suisse'
    AUSTRIA = 'AT', 'Autriche'
    POLAND = 'PL', 'Pologne'
    CZECH_REPUBLIC = 'CZ', 'République Tchèque'
    HUNGARY = 'HU', 'Hongrie'
    ROMANIA = 'RO', 'Roumanie'
    BULGARIA = 'BG', 'Bulgarie'
    CROATIA = 'HR', 'Croatie'
    SERBIA = 'RS', 'Serbie'
    SLOVAKIA = 'SK', 'Slovaquie'
    SLOVENIA = 'SI', 'Slovénie'
    LITHUANIA = 'LT', 'Lituanie'
    LATVIA = 'LV', 'Lettonie'
    ESTONIA = 'EE', 'Estonie'
    FINLAND = 'FI', 'Finlande'
    SWEDEN = 'SE', 'Suède'
    NORWAY = 'NO', 'Norvège'
    DENMARK = 'DK', 'Danemark'
    ICELAND = 'IS', 'Islande'
    IRELAND = 'IE', 'Irlande'
    LUXEMBOURG = 'LU', 'Luxembourg'
    MALTA = 'MT', 'Malte'
    CYPRUS = 'CY', 'Chypre'
    GREECE = 'GR', 'Grèce'
    TURKEY = 'TR', 'Turquie'
    RUSSIA = 'RU', 'Russie'
    UKRAINE = 'UA', 'Ukraine'
    BELARUS = 'BY', 'Biélorussie'
    MOLDOVA = 'MD', 'Moldavie'
    GEORGIA = 'GE', 'Géorgie'
    ARMENIA = 'AM', 'Arménie'
    AZERBAIJAN = 'AZ', 'Azerbaïdjan'
    KAZAKHSTAN = 'KZ', 'Kazakhstan'
    UZBEKISTAN = 'UZ', 'Ouzbékistan'
    KYRGYZSTAN = 'KG', 'Kirghizistan'
    TAJIKISTAN = 'TJ', 'Tadjikistan'
    TURKMENISTAN = 'TM', 'Turkménistan'
    AFGHANISTAN = 'AF', 'Afghanistan'
    PAKISTAN = 'PK', 'Pakistan'
    INDIA = 'IN', 'Inde'
    BANGLADESH = 'BD', 'Bangladesh'
    SRI_LANKA = 'LK', 'Sri Lanka'
    NEPAL = 'NP', 'Népal'
    BHUTAN = 'BT', 'Bhoutan'
    MALDIVES = 'MV', 'Maldives'
    CHINA = 'CN', 'Chine'
    JAPAN = 'JP', 'Japon'
    SOUTH_KOREA = 'KR', 'Corée du Sud'
    NORTH_KOREA = 'KP', 'Corée du Nord'
    MONGOLIA = 'MN', 'Mongolie'
    TAIWAN = 'TW', 'Taïwan'
    HONG_KONG = 'HK', 'Hong Kong'
    MACAU = 'MO', 'Macao'
    SINGAPORE = 'SG', 'Singapour'
    MALAYSIA = 'MY', 'Malaisie'
    THAILAND = 'TH', 'Thaïlande'
    VIETNAM = 'VN', 'Vietnam'
    CAMBODIA = 'KH', 'Cambodge'
    LAOS = 'LA', 'Laos'
    MYANMAR = 'MM', 'Myanmar'
    PHILIPPINES = 'PH', 'Philippines'
    INDONESIA = 'ID', 'Indonésie'
    BRUNEI = 'BN', 'Brunei'
    EAST_TIMOR = 'TL', 'Timor Oriental'
    AUSTRALIA = 'AU', 'Australie'
    NEW_ZEALAND = 'NZ', 'Nouvelle-Zélande'
    PAPUA_NEW_GUINEA = 'PG', 'Papouasie-Nouvelle-Guinée'
    FIJI = 'FJ', 'Fidji'
    SOLOMON_ISLANDS = 'SB', 'Îles Salomon'
    VANUATU = 'VU', 'Vanuatu'
    SAMOA = 'WS', 'Samoa'
    TONGA = 'TO', 'Tonga'
    KIRIBATI = 'KI', 'Kiribati'
    TUVALU = 'TV', 'Tuvalu'
    NAURU = 'NR', 'Nauru'
    PALAU = 'PW', 'Palaos'
    MARSHALL_ISLANDS = 'MH', 'Îles Marshall'
    MICRONESIA = 'FM', 'Micronésie'
    CANADA = 'CA', 'Canada'
    MEXICO = 'MX', 'Mexique'
    GUATEMALA = 'GT', 'Guatemala'
    BELIZE = 'BZ', 'Belize'
    EL_SALVADOR = 'SV', 'Salvador'
    HONDURAS = 'HN', 'Honduras'
    NICARAGUA = 'NI', 'Nicaragua'
    COSTA_RICA = 'CR', 'Costa Rica'
    PANAMA = 'PA', 'Panama'
    CUBA = 'CU', 'Cuba'
    JAMAICA = 'JM', 'Jamaïque'
    HAITI = 'HT', 'Haïti'
    DOMINICAN_REPUBLIC = 'DO', 'République Dominicaine'
    PUERTO_RICO = 'PR', 'Porto Rico'
    TRINIDAD_AND_TOBAGO = 'TT', 'Trinité-et-Tobago'
    BARBADOS = 'BB', 'Barbade'
    SAINT_LUCIA = 'LC', 'Sainte-Lucie'
    SAINT_VINCENT_AND_THE_GRENADINES = 'VC', 'Saint-Vincent-et-les-Grenadines'
    GRENADA = 'GD', 'Grenade'
    ANTIGUA_AND_BARBUDA = 'AG', 'Antigua-et-Barbuda'
    SAINT_KITTS_AND_NEVIS = 'KN', 'Saint-Kitts-et-Nevis'
    DOMINICA = 'DM', 'Dominique'
    BAHAMAS = 'BS', 'Bahamas'
    BRAZIL = 'BR', 'Brésil'
    ARGENTINA = 'AR', 'Argentine'
    CHILE = 'CL', 'Chili'
    URUGUAY = 'UY', 'Uruguay'
    PARAGUAY = 'PY', 'Paraguay'
    BOLIVIA = 'BO', 'Bolivie'
    PERU = 'PE', 'Pérou'
    ECUADOR = 'EC', 'Équateur'
    COLOMBIA = 'CO', 'Colombie'
    VENEZUELA = 'VE', 'Venezuela'
    GUYANA = 'GY', 'Guyana'
    SURINAME = 'SR', 'Suriname'
    FRENCH_GUIANA = 'GF', 'Guyane Française'
    SOUTH_AFRICA = 'ZA', 'Afrique du Sud'
    NAMIBIA = 'NA', 'Namibie'
    BOTSWANA = 'BW', 'Botswana'
    ZIMBABWE = 'ZW', 'Zimbabwe'
    ZAMBIA = 'ZM', 'Zambie'
    MALAWI = 'MW', 'Malawi'
    MOZAMBIQUE = 'MZ', 'Mozambique'
    MADAGASCAR = 'MG', 'Madagascar'
    MAURITIUS = 'MU', 'Maurice'
    SEYCHELLES = 'SC', 'Seychelles'
    COMOROS = 'KM', 'Comores'
    MAYOTTE = 'YT', 'Mayotte'
    REUNION = 'RE', 'Réunion'
    EGYPT = 'EG', 'Égypte'
    LIBYA = 'LY', 'Libye'
    TUNISIA = 'TN', 'Tunisie'
    ALGERIA = 'DZ', 'Algérie'
    MOROCCO = 'MA', 'Maroc'
    WESTERN_SAHARA = 'EH', 'Sahara Occidental'
    SUDAN = 'SD', 'Soudan'
    SOUTH_SUDAN = 'SS', 'Soudan du Sud'
    ETHIOPIA = 'ET', 'Éthiopie'
    ERITREA = 'ER', 'Érythrée'
    DJIBOUTI = 'DJ', 'Djibouti'
    SOMALIA = 'SO', 'Somalie'
    KENYA = 'KE', 'Kenya'
    UGANDA = 'UG', 'Ouganda'
    TANZANIA = 'TZ', 'Tanzanie'
    RWANDA = 'RW', 'Rwanda'
    BURUNDI = 'BI', 'Burundi'
    CENTRAL_AFRICAN_REPUBLIC = 'CF', 'République Centrafricaine'
    CHAD = 'TD', 'Tchad'
    CAMEROON = 'CM', 'Cameroun'
    NIGERIA = 'NG', 'Nigeria'
    NIGER = 'NE', 'Niger'
    BURKINA_FASO = 'BF', 'Burkina Faso'
    MALI = 'ML', 'Mali'
    SENEGAL = 'SN', 'Sénégal'
    GAMBIA = 'GM', 'Gambie'
    GUINEA_BISSAU = 'GW', 'Guinée-Bissau'
    GUINEA = 'GN', 'Guinée'
    SIERRA_LEONE = 'SL', 'Sierra Leone'
    LIBERIA = 'LR', 'Libéria'
    IVORY_COAST = 'CI', 'Côte d\'Ivoire'
    GHANA = 'GH', 'Ghana'
    TOGO = 'TG', 'Togo'
    BENIN = 'BJ', 'Bénin'
    MAURITANIA = 'MR', 'Mauritanie'
    CAPE_VERDE = 'CV', 'Cap-Vert'
    SAO_TOME_AND_PRINCIPE = 'ST', 'São Tomé-et-Príncipe'
    EQUATORIAL_GUINEA = 'GQ', 'Guinée Équatoriale'
    GABON = 'GA', 'Gabon'
    CONGO = 'CG', 'Congo'
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 'CD', 'République Démocratique du Congo'
    ANGOLA = 'AO', 'Angola'
    ZAMBIA = 'ZM', 'Zambie'
    ZIMBABWE = 'ZW', 'Zimbabwe'
    BOTSWANA = 'BW', 'Botswana'
    NAMIBIA = 'NA', 'Namibie'
    SOUTH_AFRICA = 'ZA', 'Afrique du Sud'
    LESOTHO = 'LS', 'Lesotho'
    SWAZILAND = 'SZ', 'Eswatini'
    ISRAEL = 'IL', 'Israël'
    PALESTINE = 'PS', 'Palestine'
    JORDAN = 'JO', 'Jordanie'
    LEBANON = 'LB', 'Liban'
    SYRIA = 'SY', 'Syrie'
    IRAQ = 'IQ', 'Irak'
    IRAN = 'IR', 'Iran'
    SAUDI_ARABIA = 'SA', 'Arabie Saoudite'
    YEMEN = 'YE', 'Yémen'
    OMAN = 'OM', 'Oman'
    UNITED_ARAB_EMIRATES = 'AE', 'Émirats Arabes Unis'
    QATAR = 'QA', 'Qatar'
    BAHRAIN = 'BH', 'Bahreïn'
    KUWAIT = 'KW', 'Koweït'
    IRAQ = 'IQ', 'Irak'
    IRAN = 'IR', 'Iran'
    AFGHANISTAN = 'AF', 'Afghanistan'
    PAKISTAN = 'PK', 'Pakistan'
    INDIA = 'IN', 'Inde'
    BANGLADESH = 'BD', 'Bangladesh'
    SRI_LANKA = 'LK', 'Sri Lanka'
    NEPAL = 'NP', 'Népal'
    BHUTAN = 'BT', 'Bhoutan'
    MALDIVES = 'MV', 'Maldives'
    CHINA = 'CN', 'Chine'
    JAPAN = 'JP', 'Japon'
    SOUTH_KOREA = 'KR', 'Corée du Sud'
    NORTH_KOREA = 'KP', 'Corée du Nord'
    MONGOLIA = 'MN', 'Mongolie'
    TAIWAN = 'TW', 'Taïwan'
    HONG_KONG = 'HK', 'Hong Kong'
    MACAU = 'MO', 'Macao'
    SINGAPORE = 'SG', 'Singapour'
    MALAYSIA = 'MY', 'Malaisie'
    THAILAND = 'TH', 'Thaïlande'
    VIETNAM = 'VN', 'Vietnam'
    CAMBODIA = 'KH', 'Cambodge'
    LAOS = 'LA', 'Laos'
    MYANMAR = 'MM', 'Myanmar'
    PHILIPPINES = 'PH', 'Philippines'
    INDONESIA = 'ID', 'Indonésie'
    BRUNEI = 'BN', 'Brunei'
    EAST_TIMOR = 'TL', 'Timor Oriental'
    AUSTRALIA = 'AU', 'Australie'
    NEW_ZEALAND = 'NZ', 'Nouvelle-Zélande'
    PAPUA_NEW_GUINEA = 'PG', 'Papouasie-Nouvelle-Guinée'
    FIJI = 'FJ', 'Fidji'
    SOLOMON_ISLANDS = 'SB', 'Îles Salomon'
    VANUATU = 'VU', 'Vanuatu'
    SAMOA = 'WS', 'Samoa'
    TONGA = 'TO', 'Tonga'
    KIRIBATI = 'KI', 'Kiribati'
    TUVALU = 'TV', 'Tuvalu'
    NAURU = 'NR', 'Nauru'
    PALAU = 'PW', 'Palaos'
    MARSHALL_ISLANDS = 'MH', 'Îles Marshall'
    MICRONESIA = 'FM', 'Micronésie'

