# Generated by Django 4.2.24 on 2025-09-08 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("widgets", models.JSONField(default=list)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Dashboard d'administration",
                "verbose_name_plural": "Dashboards d'administration",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(default="general", max_length=50)),
                ("is_public", models.BooleanField(default=False)),
                ("is_encrypted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuration système",
                "verbose_name_plural": "Configurations système",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="AdminReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("users", "Utilisateurs"),
                            ("activity", "Activité"),
                            ("security", "Sécurité"),
                            ("performance", "Performance"),
                            ("system", "Système"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("parameters", models.JSONField(default=dict)),
                ("results", models.JSONField(default=dict)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("is_scheduled", models.BooleanField(default=False)),
                ("schedule_cron", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport d'administration",
                "verbose_name_plural": "Rapports d'administration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("error", "Erreur"),
                            ("critical", "Critique"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("target_model", models.CharField(blank=True, max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=50)),
                ("message", models.TextField()),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'administration",
                "verbose_name_plural": "Logs d'administration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("user_create", "Création d'utilisateur"),
                            ("user_update", "Modification d'utilisateur"),
                            ("user_delete", "Suppression d'utilisateur"),
                            ("user_activate", "Activation d'utilisateur"),
                            ("user_deactivate", "Désactivation d'utilisateur"),
                            ("user_suspend", "Suspension d'utilisateur"),
                            ("user_unsuspend", "Réactivation d'utilisateur"),
                            ("permission_grant", "Octroi de permission"),
                            ("permission_revoke", "Révocation de permission"),
                            ("role_assign", "Attribution de rôle"),
                            ("role_unassign", "Suppression de rôle"),
                            ("group_add", "Ajout à un groupe"),
                            ("group_remove", "Suppression d'un groupe"),
                            ("system_config", "Configuration système"),
                            ("backup_create", "Création de sauvegarde"),
                            ("backup_restore", "Restauration de sauvegarde"),
                            ("log_export", "Export de logs"),
                            ("data_export", "Export de données"),
                            ("data_import", "Import de données"),
                            ("security_alert", "Alerte de sécurité"),
                            ("maintenance_mode", "Mode maintenance"),
                            ("cache_clear", "Vidage du cache"),
                            ("email_send", "Envoi d'email"),
                            ("notification_send", "Envoi de notification"),
                            ("api_key_create", "Création de clé API"),
                            ("api_key_revoke", "Révocation de clé API"),
                            ("integration_create", "Création d'intégration"),
                            ("integration_update", "Modification d'intégration"),
                            ("integration_delete", "Suppression d'intégration"),
                        ],
                        max_length=50,
                        verbose_name="Type d'action",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("in_progress", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("normal", "Normal"),
                            ("high", "Élevé"),
                            ("urgent", "Urgent"),
                            ("critical", "Critique"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="Priorité",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                ("details", models.JSONField(default=dict, verbose_name="Détails")),
                ("result", models.JSONField(default=dict, verbose_name="Résultat")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Message d'erreur"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Clé de session"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Début"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Fin"),
                ),
                (
                    "duration",
                    models.DurationField(blank=True, null=True, verbose_name="Durée"),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Administrateur",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_admin_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur cible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Action d'administration",
                "verbose_name_plural": "Actions d'administration",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action_type"], name="admin_api_a_action__ca91af_idx"
                    ),
                    models.Index(
                        fields=["status"], name="admin_api_a_status_851db3_idx"
                    ),
                    models.Index(
                        fields=["admin_user"], name="admin_api_a_admin_u_dc46c5_idx"
                    ),
                    models.Index(
                        fields=["target_user"], name="admin_api_a_target__37e0b4_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="admin_api_a_created_2403e8_idx"
                    ),
                ],
            },
        ),
    ]
