# Generated by Django 4.2.24 on 2025-09-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("api", "API"),
                    ("auth", "Authentication"),
                    ("user", "User"),
                    ("admin", "Admin"),
                    ("security", "Security"),
                    ("system", "System"),
                    ("database", "Database"),
                    ("external", "External Service"),
                    ("monitoring", "Monitoring"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
