# Generated by Django 4.2.24 on 2025-09-09 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("page", "Page"),
                            ("article", "Article"),
                            ("product", "Produit"),
                            ("category", "Catégorie"),
                            ("menu", "Menu"),
                            ("widget", "Widget"),
                            ("form", "Formulaire"),
                            ("email_template", "Template Email"),
                            ("notification_template", "Template Notification"),
                            ("api_message", "Message API"),
                            ("seo_meta", "Méta SEO"),
                        ],
                        max_length=30,
                    ),
                ),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                (
                    "content_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Contenu",
                "verbose_name_plural": "Contenus",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentTranslation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("translated_title", models.CharField(max_length=255)),
                ("translated_description", models.TextField(blank=True)),
                ("translated_content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_review", "En Attente de Révision"),
                            ("approved", "Approuvé"),
                            ("published", "Publié"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("translated_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "translation_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Bon"),
                            ("fair", "Correct"),
                            ("poor", "Médiocre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.TextField(blank=True)),
                ("slug", models.SlugField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Traduction de Contenu",
                "verbose_name_plural": "Traductions de Contenu",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("es", "Español"),
                            ("de", "Deutsch"),
                            ("it", "Italiano"),
                            ("pt", "Português"),
                            ("ru", "Русский"),
                            ("zh", "中文"),
                            ("ja", "日本語"),
                            ("ko", "한국어"),
                            ("ar", "العربية"),
                            ("hi", "हिन्दी"),
                            ("th", "ไทย"),
                            ("vi", "Tiếng Việt"),
                            ("tr", "Türkçe"),
                            ("pl", "Polski"),
                            ("nl", "Nederlands"),
                            ("sv", "Svenska"),
                            ("da", "Dansk"),
                            ("no", "Norsk"),
                            ("fi", "Suomi"),
                            ("cs", "Čeština"),
                            ("hu", "Magyar"),
                            ("ro", "Română"),
                            ("bg", "Български"),
                            ("hr", "Hrvatski"),
                            ("sk", "Slovenčina"),
                            ("sl", "Slovenščina"),
                            ("et", "Eesti"),
                            ("lv", "Latviešu"),
                            ("lt", "Lietuvių"),
                            ("mt", "Malti"),
                            ("cy", "Cymraeg"),
                            ("ga", "Gaeilge"),
                            ("eu", "Euskera"),
                            ("ca", "Català"),
                            ("gl", "Galego"),
                        ],
                        max_length=5,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("native_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_rtl", models.BooleanField(default=False)),
                ("flag_emoji", models.CharField(blank=True, max_length=10)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("auto_translate_enabled", models.BooleanField(default=True)),
                (
                    "translation_quality",
                    models.CharField(
                        choices=[
                            ("high", "Haute"),
                            ("medium", "Moyenne"),
                            ("low", "Faible"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("translation_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Langue",
                "verbose_name_plural": "Langues",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("translated_text", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("auto_translated", "Traduit Automatiquement"),
                            ("human_translated", "Traduit par un Humain"),
                            ("reviewed", "Révisé"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("translation_service", models.CharField(blank=True, max_length=50)),
                ("translated_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="internationalization.language",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translations_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "translated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="translations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Traduction",
                "verbose_name_plural": "Traductions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranslationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("source_text", models.TextField()),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("ui", "Interface Utilisateur"),
                            ("email", "Email"),
                            ("notification", "Notification"),
                            ("error", "Message d'Erreur"),
                            ("success", "Message de Succès"),
                            ("warning", "Avertissement"),
                            ("help", "Aide"),
                            ("documentation", "Documentation"),
                            ("api", "API"),
                            ("admin", "Administration"),
                            ("content", "Contenu"),
                            ("seo", "SEO"),
                        ],
                        default="ui",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "Haute"),
                            ("medium", "Moyenne"),
                            ("low", "Faible"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("processing", "En Cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("use_auto_translation", models.BooleanField(default=True)),
                ("require_human_review", models.BooleanField(default=False)),
                ("translation_service", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_translations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="source_requests",
                        to="internationalization.translation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_requests",
                        to="internationalization.language",
                    ),
                ),
                (
                    "target_languages",
                    models.ManyToManyField(
                        related_name="target_requests",
                        to="internationalization.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de Traduction",
                "verbose_name_plural": "Demandes de Traduction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TranslationKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("ui", "Interface Utilisateur"),
                            ("email", "Email"),
                            ("notification", "Notification"),
                            ("error", "Message d'Erreur"),
                            ("success", "Message de Succès"),
                            ("warning", "Avertissement"),
                            ("help", "Aide"),
                            ("documentation", "Documentation"),
                            ("api", "API"),
                            ("admin", "Administration"),
                            ("content", "Contenu"),
                            ("seo", "SEO"),
                        ],
                        default="ui",
                        max_length=20,
                    ),
                ),
                ("source_text", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "Haute"),
                            ("medium", "Moyenne"),
                            ("low", "Faible"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                (
                    "source_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_keys",
                        to="internationalization.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clé de Traduction",
                "verbose_name_plural": "Clés de Traduction",
                "ordering": ["key"],
            },
        ),
        migrations.AddField(
            model_name="translation",
            name="translation_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="internationalization.translationkey",
            ),
        ),
        migrations.CreateModel(
            name="LanguagePreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("auto_detect_language", models.BooleanField(default=True)),
                ("show_original_text", models.BooleanField(default=False)),
                ("fallback_to_english", models.BooleanField(default=True)),
                ("auto_translate_enabled", models.BooleanField(default=True)),
                ("translation_confidence_threshold", models.FloatField(default=0.8)),
                ("prefer_human_translation", models.BooleanField(default=True)),
                ("browser_language", models.CharField(blank=True, max_length=10)),
                ("timezone", models.CharField(blank=True, max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "primary_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_users",
                        to="internationalization.language",
                    ),
                ),
                (
                    "secondary_languages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="secondary_users",
                        to="internationalization.language",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Préférence de Langue",
                "verbose_name_plural": "Préférences de Langue",
            },
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(fields=["code"], name="internation_code_788ae4_idx"),
        ),
        migrations.AddIndex(
            model_name="language",
            index=models.Index(
                fields=["is_active", "is_default"],
                name="internation_is_acti_1a39e7_idx",
            ),
        ),
        migrations.AddField(
            model_name="contenttranslation",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="internationalization.content",
            ),
        ),
        migrations.AddField(
            model_name="contenttranslation",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_translations",
                to="internationalization.language",
            ),
        ),
        migrations.AddField(
            model_name="contenttranslation",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_translations_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="contenttranslation",
            name="translated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_translations_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="content_object_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_content",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="content",
            name="source_language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="source_content",
                to="internationalization.language",
            ),
        ),
        migrations.AddIndex(
            model_name="translationrequest",
            index=models.Index(
                fields=["status", "priority"], name="internation_status_95946b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translationrequest",
            index=models.Index(
                fields=["requested_by", "created_at"],
                name="internation_request_c94e85_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="translationrequest",
            index=models.Index(
                fields=["source_language"], name="internation_source__76b377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translationkey",
            index=models.Index(fields=["key"], name="internation_key_ec61dc_idx"),
        ),
        migrations.AddIndex(
            model_name="translationkey",
            index=models.Index(
                fields=["context", "is_active"], name="internation_context_0f542d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translationkey",
            index=models.Index(
                fields=["source_language"], name="internation_source__af20ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["translation_key", "language"],
                name="internation_transla_b87a91_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["status", "is_active"], name="internation_status_db69f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["language", "status"], name="internation_languag_2889e7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("translation_key", "language")},
        ),
        migrations.AddIndex(
            model_name="contenttranslation",
            index=models.Index(
                fields=["content", "language"], name="internation_content_7b0f24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contenttranslation",
            index=models.Index(
                fields=["status", "is_active"], name="internation_status_145dc2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contenttranslation",
            index=models.Index(
                fields=["language", "status"], name="internation_languag_89872b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contenttranslation",
            unique_together={("content", "language")},
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["content_type", "identifier"],
                name="internation_content_01eb76_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["source_language", "is_active"],
                name="internation_source__c6380d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="internation_created_40aef8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="content",
            unique_together={("content_type", "identifier", "source_language")},
        ),
    ]
