# Generated by Django 4.2.24 on 2025-09-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailnotification",
            name="from_email",
            field=models.EmailField(
                default="noreply@yourdomain.com",
                max_length=254,
                verbose_name="Email expéditeur",
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="from_email",
            field=models.EmailField(
                default="noreply@yourdomain.com",
                max_length=254,
                verbose_name="Email expéditeur",
            ),
        ),
    ]
